server:
    port: 8181

## Gateway
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: gateway-service
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allow-credentials: true
                        # allowed-origins: '*'
                        # allowed-headers: '*'
                        allowed-methods: 
                            - OPTIONS
                            - GET
                            - POST
                            - PUT
            ## Discover Server Route
            routes[0]:
                id: discovery-server
                uri: http://discovery-server:8761
                predicates[0]: Path=/eureka/web
                filters[0]: SetPath=/
            ## Discover Server Static Resources Route
            routes[1]:
                id: discovery-server-static
                uri: http://discovery-server:8761
                predicates[0]: Path=/eureka/**
            ## Member Service Route
            routes[2]:
                id: member-service
                # uri: lb://member-service
                uri: http://member-service:8900/
                predicates[0]:
                    name: Path
                    args:
                        pattern: /member/**
            ## Member Service Route
            routes[3]:
                id: ess-service
                # uri: lb://ess-service
                uri: http://ess-service:8901/
                predicates[0]:
                    name: Path
                    args:
                        pattern: /ess/**
            ## Admin Service Route
            routes[4]:
                id: admin-service
                # uri: lb://admin-service
                uri: http://admin-service:8902/
                predicates[0]:
                    name: Path
                    args:
                        pattern: /admin/**
        compatibility-verifier: 
            enabled: false
    security: 
        oauth2: 
            client: 
                registraion: 
                    okta:
                        client-id: 0oabjwzqyhAd1VsxX5d7
                        client-secret: ulsmzHE7Y3qUORZf5pzHldaWC-E9rrnlD8eHS2oMM7hsy3RUPEmIOaocoRTWxSDl
                        issuer-uri: https://dev-04798219.okta.com/oauth2/default
eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-service:8761/eureka


# Actuator Prometheus Endpoint
# management:
#     zipkin:
#         tracing:
#             endpoint: http://localhost:9411/api/v2/spans
#     tracing:        
#         sampling:
#             probability: 1.0
#     endpoints:
#         web:
#             exposure:
#                 include: prometheus

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


# Can be set to false to disable security during local development
# rest: 
#     security:
#         enabled: false
#         api-matcher: /**
#         issuer-uri: http://localhost:8080/auth/realms/atlas
#         resource-id: atlasclient

# Configuration to toggle Okta security
security:
    okta:
        enabled: false # toggle this to enable/disable Okta

okta: 
    oauth2: 
        issuer: https://dev-04798219.okta.com/oauth2/default
        client-id: 0oabjwzqyhAd1VsxX5d7
        client-secret: ulsmzHE7Y3qUORZf5pzHldaWC-E9rrnlD8eHS2oMM7hsy3RUPEmIOaocoRTWxSDl